# Generated by Django 4.2.1 on 2023-05-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.CharField(max_length=100)),
                ('from_address', models.CharField(max_length=100)),
                ('to_address', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('gas_price', models.CharField(max_length=100)),
                ('gas_limit', models.CharField(max_length=100)),
                ('gas_used', models.CharField(max_length=100)),
                ('contract_address', models.CharField(max_length=100)),
                ('date', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('tr_Jtype', models.CharField(max_length=100)),
                ('block', models.IntegerField()),
                ('value', models.CharField(max_length=100)),
                ('nonce', models.IntegerField()),
                ('native_token_decimals', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('received', models.JSONField()),
                ('sent', models.JSONField()),
                ('others', models.JSONField()),
                ('input_data', models.CharField(max_length=100)),
            ],
        ),
    ]
