# Generated by Django 4.2.1 on 2023-05-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tr_Jtype',
            new_name='tr_type',
        ),
    ]
